/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        main: {
          0: 'var(--mantine-color-main-0)',
          1: 'var(--mantine-color-main-1)',
          2: 'var(--mantine-color-main-2)',
          3: 'var(--mantine-color-main-3)',
          4: 'var(--mantine-color-main-4)',
          5: 'var(--mantine-color-main-5)',
          6: 'var(--mantine-color-main-6)',
          7: 'var(--mantine-color-main-7)',
          8: 'var(--mantine-color-main-8)',
          9: 'var(--mantine-color-main-9)',
        },
        black: {
          0: 'var(--mantine-color-black-0)',
          1: 'var(--mantine-color-black-1)',
          2: 'var(--mantine-color-black-2)',
          3: 'var(--mantine-color-black-3)',
          4: 'var(--mantine-color-black-4)',
          5: 'var(--mantine-color-black-5)',
          6: 'var(--mantine-color-black-6)',
          7: 'var(--mantine-color-black-7)',
          8: 'var(--mantine-color-black-8)',
          9: 'var(--mantine-color-black-9)',
        },
        gray: {
          0: 'var(--mantine-color-gray-0)',
          1: 'var(--mantine-color-gray-1)',
          2: 'var(--mantine-color-gray-2)',
          3: 'var(--mantine-color-gray-3)',
          4: 'var(--mantine-color-gray-4)',
          5: 'var(--mantine-color-gray-5)',
          6: 'var(--mantine-color-gray-6)',
          7: 'var(--mantine-color-gray-7)',
          8: 'var(--mantine-color-gray-8)',
          9: 'var(--mantine-color-gray-9)',
        },
        blue: {
          0: 'var(--mantine-color-blue-0)',
          1: 'var(--mantine-color-blue-1)',
          2: 'var(--mantine-color-blue-2)',
          3: 'var(--mantine-color-blue-3)',
          4: 'var(--mantine-color-blue-4)',
          5: 'var(--mantine-color-blue-5)',
          6: 'var(--mantine-color-blue-6)',
          7: 'var(--mantine-color-blue-7)',
          8: 'var(--mantine-color-blue-8)',
          9: 'var(--mantine-color-blue-9)',
        },
      },
    },
  },
};
